### ISSUE TITLE
Error  retrieving data

### ISSUE THREAD

**Issue by cloudsantos** [Microsoft/ApplicationInsights-Docker#23]
Hi,
 i have configured and ran the docker images/container but when i go to the Azure/Application insight portal i receive the 'Error Retrieving Data',

The container log is:
......

Starting to collect events from: MetricCollectionPythonBoostrapper
docker : Traceback (most recent call last):
At line:1 char:1
+ docker logs --tail=30 3657bfccd9fa *> log.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "python/bootstrap.py", line 49, in <module>
    methods[method]()
  File "python/bootstrap.py", line 43, in <lambda>
    methods = {'collect': lambda: program.run_collect_performance_counters(docker_socket=_docker_socket, 
sdk_file=_sdk_info_file, docker_info_file=_docker_info_path, collect_interval=collect_interval),

  File "/usr/docker/ApplicationInsights-Docker/build/docker/python/appinsights/program.py", line 49, in 
run_collect_performance_counters

    collector.collect_stats_and_send()

  File "/usr/docker/ApplicationInsights-Docker/build/docker/python/appinsights/dockercollector.py", line 76, in 
collect_stats_and_send

    self._update_containers_state(containers=containers)

  File "/usr/docker/ApplicationInsights-Docker/build/docker/python/appinsights/dockercollector.py", line 175, in 
_update_containers_state

    list(executor.map(lambda c: self._update_container_state(c), containers))

  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 549, in result_iterator

    yield future.result()

  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 395, in result

    return self.__get_result()

  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result

    raise self._exception

  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/docker/ApplicationInsights-Docker/build/docker/python/appinsights/dockercollector.py", line 175, in 
<lambda>

    list(executor.map(lambda c: self._update_container_state(c), containers))

  File "/usr/docker/ApplicationInsights-Docker/build/docker/python/appinsights/dockercollector.py", line 181, in 
_update_container_state

    ikey = self._get_container_sdk_ikey(container)

  File "/usr/docker/ApplicationInsights-Docker/build/docker/python/appinsights/dockercollector.py", line 205, in 
_get_container_sdk_ikey

    return None if sdk_info_file_content is None else sdk_info_file_content.split('=')[1]

IndexError: list index out of range

Python bootstrapper MetricCollectionPythonBoostrapper has exited with exit code: 1

**Comment by cloudsantos** [comment]
Docker version

Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      ucp/1.0.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   ef7f862
 Built:
 OS/Arch:      linux/amd64

**Comment by Yonisha** [comment]
Hi cloudsantos,

The issue has been fixed in v0.9.2.
Can you please pull the latest version and check if the issue resolved?

**Comment by cloudsantos** [comment]
Issue solved ☺!!!
Thank you
Best regards
Santo

Santo Orlando | Cloud Solution Architect
Avanade Italy| Piazzale dell’Industria,40, Roma
Mobile: +39 3481434120
www.avanade.com<http://www.avanade.com/>
